### ISSUE TITLE
How to use config?

### ISSUE THREAD

**Issue by gixxy22** [ostark/craft-relax#11]
I see the config option here:

` 'searchIndexInsertFilter' => [],`

But what do i put here? an array of attributes and keywords like this?

```
    'searchIndexInsertFilter' => [
        'attribute' => 'slug',
        'keywords' => 'group of keywords'
    ],
```

What does `keywords` match? exact match? can I use regex to match `.*` ?

Any help appreciated, as I have a large table of 10M+, and  will take a long time to re-index, so ideally want to get it right first time.

thanks!

**Comment by ostark** [comment]
The `searchIndexInsertFilter` accepts a list of classes that implement https://github.com/ostark/craft-relax/blob/main/src/SearchIndex/InsertFilter.php
