### ISSUE TITLE
Installing plugin from Craft's Plugin store installed v2.0.0 even though a v2.0.1 is available [BUG]

### ISSUE THREAD

**Issue by icreatestuff** [ostark/craft-relax#13]
Issue as stated in the title of the post.

I only realised it was a problem having also installed the Async Queue plugin and investigating why the queued jobs weren't being processed. I saw in the queue log the `Queue must be an application component.` exception being thrown which lead me to the Relax changelog and mention of that error being fixed in the 2.0.1 release.

I had to manually update `composer.json` to specify 2.0.1 and run `composer update` as no updates were listed in Crafts > Utilities > Updates area.

Seems like the plugin store just isn't aware of the newest version?

Thanks for the great work.

**Comment by ostark** [comment]
Thanks for letting me know.
It's strange, packagist is aware of 2.0.1 https://packagist.org/packages/ostark/craft-relax

but the plugin store is not up-to-date
https://github.com/ostark/craft-relax/blob/main/CHANGELOG.md

I'll leave this open - hopefully the next release will fix it.
