### ISSUE TITLE
[BUG] Plugin is not working with the latest Craft-Blitz release (4.9.3)

### ISSUE THREAD

**Issue by lukasNo1** [ostark/craft-relax#16]
See also the issue at https://github.com/putyourlightson/craft-blitz/issues/591

This error is only thrown if the relax plugin is enabled.

I use relax v 2.0.1

`Queue must be an application component. {"trace":["#0 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(836): craft\\queue\\Queue->componentId()","#1 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(645): craft\\queue\\Queue->channel()","#2 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2-queue/src/Queue.php(193): craft\\queue\\Queue->pushMessage('O:42:\"putyourli...', 300, 0, 10)","#3 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(259): yii\\queue\\Queue->push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob))","#4 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/helpers/Queue.php(56): craft\\queue\\Queue->push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob))","#5 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(344): craft\\helpers\\Queue::push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob), 10, NULL, NULL, Object(craft\\queue\\Queue))","#6 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(254): putyourlightson\\blitz\\services\\RefreshCacheService->refresh()","#7 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/Blitz.php(384): putyourlightson\\blitz\\services\\RefreshCacheService->addElement(Object(craft\\elements\\Entry))","#8 [internal function]: putyourlightson\\blitz\\Blitz->putyourlightson\\blitz\\{closure}(Object(craft\\events\\ElementEvent))","#9 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\\events\\ElementEvent))","#10 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('craft\\\\services\\\\...', 'afterSaveElemen...', Object(craft\\events\\ElementEvent))","#11 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(3533): yii\\base\\Component->trigger('afterSaveElemen...', Object(craft\\events\\ElementEvent))","#12 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(1615): craft\\services\\Elements->_saveElementInternal(Object(craft\\elements\\Entry), false, false, true, Array)","#13 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(1261): craft\\services\\Elements->duplicateElement(Object(craft\\elements\\Entry), Array)","#14 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Drafts.php(305): craft\\services\\Elements->updateCanonicalElement(Object(craft\\elements\\Entry), Array)","#15 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/controllers/ElementsController.php(1550): craft\\services\\Drafts->applyDraft(Object(craft\\elements\\Entry))","#16 [internal function]: craft\\controllers\\ElementsController->actionApplyDraft()","#17 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#18 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#19 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('apply-draft', Array)","#20 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(305): yii\\base\\Module->runAction('elements/apply-...', Array)","#21 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(606): craft\\web\\Application->runAction('elements/apply-...', Array)","#22 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(284): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))","#23 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","#24 /var/www/vhosts/project/project/current/public/index.php(14): yii\\base\\Application->run()","#25 {main}"],"memory":8547704,"exception":"[object] (yii\\base\\InvalidConfigException(code: 0): Queue must be an application component. at /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php:695)"}`

**Comment by ostark** [comment]
Hey @lukasNo1 
please update your Relax plugin. 
The latest version works with the latest changes in Blitz.

**Comment by lukasNo1** [comment]
Thank you @ostark, it works now!

**Comment by hiasl** [comment]
Hi @ostark 
could you please do me (and maybe others) a favor and backport version 2's Extrawurst to version 1.x of Relax as well? we are still on Craft 3 with Relax and Blitz...
thanks

**Comment by hiasl** [comment]
this is the pull request for it to be used as 1.0.2: https://github.com/ostark/craft-relax/pull/17
