### ISSUE TITLE
"This plugin requires PHP ^7.4 | ^8.0, but your composer.json file is currently set to 8.0."

### ISSUE THREAD

**Issue by howells** [ostark/craft-relax#2]
Not sure if this is Relax-specific, but when I try to install this plugin, the plugin page shows 

"This plugin requires PHP ^7.4 | ^8.0, but your composer.json file is currently set to 8.0."

What should my composer.json be set to to satisfy the requirement?

**Comment by ostark** [comment]
@howells That's odd, can you try the `fix/composer-php` branch please?

```
"ostark/craft-relax": "dev-fix/composer-php"
```

**Comment by philipzaengle** [comment]
@ostark thanks for this plugin. When using this branch I get the error

```  Problem 1
    - laminas/laminas-feed 2.12.3 requires php ^5.6 || ^7.0 -> your php version (8.0; overridden via config.platform, actual: 8.0.8) does not satisfy that requirement.
    - craftcms/cms 3.7.30.1 requires laminas/laminas-feed ~2.12.3|^2.13.1 -> satisfiable by laminas/laminas-feed[2.12.3].
    - craftcms/cms is locked to version 3.7.30.1 and an update of this package was not requested.```

using Composer version 2.0.9 2

**Comment by ostark** [comment]
@philipzaengle same issue with th
