### ISSUE TITLE
Ability to change queue ttr (time to reserve)

### ISSUE THREAD

**Issue by KarlBishop** [ostark/craft-relax#3]
We have occasional long-running queue jobs, like Blitz Cache Warmer and FeedMe imports, that need a very large `ttr` (time to reserve).

Is there a way I can increase `ttr` when using this plugin?

I have a custom value set in app.php (`'components' => [ 'queue' => [ 'ttr' => 1800`) but new jobs are now created with ttr of `300`.

Great work anyway! If it's not possible at the moment then I'd be interested to know what you think of this as a feature request.

**Comment by ostark** [comment]
I'll look into this.

**Comment by KarlBishop** [comment]
Fantastic - thanks!
