### ISSUE TITLE
Reporting issues might not be working on this repo

### ISSUE THREAD

**Issue by KarlBishop** [ostark/craft-relax#6]
I've opened two issues previously and neither seemed to get noticed on GitHub. (Although the first issue was addressed when I got in touch via another means...)

I'm wondering if issue notifications are not working on this repo?

I suspect this might be the case because all the links on the [New Issue page](https://github.com/ostark/craft-relax/issues/new/choose) are broken - they have colons in the URLs that shouldn't be there - so maybe these colons are causing problems elsewhere in the system ...?

**Comment by tekstrand** [comment]
Curious, I just came to check my issue that I opened yesterday and found it doesn't exist.

**Comment by ostark** [comment]
Now I understand the actual "issue". 
Thanks for letting me know!
