### ISSUE TITLE
[BUG] Is there a version for Craft v3?

### ISSUE THREAD

**Issue by iamkeir** [ostark/craft-relax#9]
When trying to install, we receive the following error:

```
Your requirements could not be resolved to an installable set of packages.
ostark/craft-relax 2.0.0 requires craftcms/cms ^4.0.0
```

Thanks!

**Comment by iamkeir** [comment]
I was able to install `ostark/craft-relax 1.0.1` - is the last Craft v3 compatible version?

**Comment by ostark** [comment]
Yes, 1.0.1 is the last release for Craft 3
